- name: default
  hosts: web
  tasks:
  - name: default value
    ansible.builtin.debug:
      msg: "hello {{course | default('ansible')}}"

- name: upper case
  hosts: web
  vars:
    greeting: "good moring"
  tasks:  
  - name: upper case
    ansible.builtin.debug:
      msg: "{{greeting | upper }}"        