- name: default
  hosts: web
  tasks:
  - name: default value
    ansible.builtin.debug:
      msg: "hello {{course | default('ansible')}}"

- name: upper case
  hosts: web
  vars:
    greeting: "HELLO,good moring"
  tasks:  
  - name: upper case
    ansible.builtin.debug:
      msg: "{{greeting | upper }}"        

- name: lower case
  hosts: web
  vars:
    greeting: "HELLO,good moring"
  tasks:  
  - name: lower case
    ansible.builtin.debug:
      msg: "{{greeting | lower }}"            

- name: duplicates
  hosts: web
  vars:
    numbers: [1, 2, 2, 3, 3, 4, 5] 
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{ numbers | unique}}"       