- name: loops install
  hosts: web
  become: yes
  tasks:
  - name: install pack
    ansible.builtin.dnf:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'mysql', state: 'latest'} #item
    - { name: 'nginx', state: 'absent'}
    - { name: 'postfix', state: 'latest'}
  