- name: loops install
  hosts: web
  become: yes
  tasks:
  - name: install pack
    ansible.builtin.dnf:
      name: " {{ item }} "
      state: latest
    loop:
    - mysql
    - nginx
    - postfix